name: Deploy ML Model Training to EC2

on:
  push:
    branches:
      - develop  # Trigger the action when pushing to the `main` branch
  workflow_dispatch: # Allow manual trigger from GitHub UI

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: SSH to EC2 instance and run training script
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
        
            # Clone the GitHub repository if not already cloned
            if [ ! -d "model-trainer" ]; then
              git clone https://github.com/MLOpsLab/model-trainer.git
            fi
            
            cd model-trainer
            
            # Create a .env file with environment variables (without pushing it to GitHub)
            echo "ALIAS=${{ secrets.ALIAS }}" > .env
            echo "MODEL_NAME=${{ secrets.MODEL_NAME }}" >> .env
            echo "MLFLOW_TRACKING_URI=${{ secrets.MLFLOW_TRACKING_URI }}" >> .env
            echo "DATASET_URI=${{ secrets.DATASET_URI }}" >> .env
            echo "ARTIFACT_URI=${{ secrets.ARTIFACT_URI }}" >> .env
            
            # Pull the latest changes
            git pull origin main
            
            # Build the Docker image
            docker build -t model-trainer .
            
            # Create a custom network (if it doesn't exist)
            docker network create --driver bridge mlops-lab-net || true
            
            # Stop any running containers (in case there's an older one)
            docker stop model-trainer || true
            docker rm model-trainer || true
            
            # Run the model training in the container
            docker run --name model-trainer --env-file .env model-trainer
