name: Deploy ML Model Training to EC2

on:
  push:
    branches:
      - develop  # Trigger on develop branch
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: SSH to EC2 instance and run training script
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Clone or update the repo
            if [ ! -d "model-trainer" ]; then
              git clone https://github.com/MLOpsLab/model-trainer.git
            fi

            cd model-trainer
            git fetch origin
            git checkout develop
            git pull origin develop

            # Create .env file with secrets
            echo "ALIAS=${{ secrets.ALIAS }}" > .env
            echo "MODEL_NAME=${{ secrets.MODEL_NAME }}" >> .env
            echo "MLFLOW_TRACKING_URI=${{ secrets.MLFLOW_TRACKING_URI }}" >> .env
            echo "DATASET_URI=${{ secrets.DATASET_URI }}" >> .env
            echo "S3_BUCKET=${{ secrets.S3_BUCKET }}" >> .env

            echo "=== .env contents ==="
            cat .env

            # Build and run Docker container
            docker build --no-cache -t model-trainer .
            docker network create --driver bridge mlops-lab-net || true
            docker stop model-trainer || true
            docker rm model-trainer || true
            docker run --name model-trainer --env-file .env model-trainer
